### ISSUE TITLE
Error: Node-gyp rebuild!

### ISSUE THREAD

**Issue by lednhatkhanh** [fusion809/terminal-fusion#1]
> pty.js@0.3.1 install C:\Users\lednh\AppData\Local\Temp\apm-install-dir-116818-5124-1sbvn4o\node_modules\terminal-fusion\node_modules\pty.js
> node-gyp rebuild

C:\Users\lednh\AppData\Local\Temp\apm-install-dir-116818-5124-1sbvn4o\node_modules\terminal-fusion\node_modules\pty.js>if not defined npm_config_node_gyp (node "C:\Users\lednh\AppData\Local\atom\app-1.10.2\resources\app\apm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\lednh\AppData\Local\atom\app-1.10.2\resources\app\apm\bin\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
C:\Users\lednh\AppData\Local\Temp\apm-install-dir-116818-5124-1sbvn4o
`-- (empty)

gyp: deps\winpty\winpty.gyp not found (cwd: C:\Users\lednh\AppData\Local\Temp\apm-install-dir-116818-5124-1sbvn4o\node_modules\terminal-fusion\node_modules\pty.js) while loading dependencies of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\lednh\AppData\Local\atom\app-1.10.2\resources\app\apm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\Users\lednh\AppData\Local\atom\app-1.10.2\resources\app\apm\bin\node.exe" "C:\Users\lednh\AppData\Local\atom\app-1.10.2\resources\app\apm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\lednh\AppData\Local\Temp\apm-install-dir-116818-5124-1sbvn4o\node_modules\terminal-fusion\node_modules\pty.js
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\lednh\AppData\Local\Temp\apm-install-dir-116818-5124-1sbvn4o\package.json'
npm WARN apm-install-dir-116818-5124-1sbvn4o No description
npm WARN apm-install-dir-116818-5124-1sbvn4o No repository field.
npm WARN apm-install-dir-116818-5124-1sbvn4o No README data
npm WARN apm-install-dir-116818-5124-1sbvn4o No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\Users\lednh\AppData\Local\atom\app-1.10.2\resources\app\apm\bin\node.exe" "C:\Users\lednh\AppData\Local\atom\app-1.10.2\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\lednh\.atom\.apm\.apmrc" "--userconfig" "C:\Users\lednh\.atom\.apmrc" "install" "C:\Users\lednh\AppData\Local\Temp\d-116818-5124-cganjg\package.tgz" "--runtime=electron" "--target=0.37.8" "--arch=ia32" "--global-style" "--msvs_version=2015"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pty.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\lednh\AppData\Local\Temp\apm-install-dir-116818-5124-1sbvn4o\npm-debug.log
npm ERR! code 1

**Comment by fusion809** [comment]
Ah, my apologies but to quote this repository's [README](https://github.com/fusion809/terminal-fusion/blob/master/README.md):

> It has been forked from the platformio-ide-terminal package, and is designed specifically for Linux platforms. If you are using macOS or Windows NT I would recommend using the platformio-ide-terminal package instead.

In other words, this package is meant for Atom running on _Linux_, not Windows NT. So I'm afraid the best I can do for you is to direct you to the [`platformio-ide-terminal`](https://github.com/platformio/platformio-atom-ide-terminal) package, which _is_ compatible with Windows NT.
