### ISSUE TITLE
internal command "cd" wont work via bash script, launched by  terminal-fusion

### ISSUE THREAD

**Issue by mikromika** [fusion809/terminal-fusion#13]
### Prerequisites
* Does this error occur on Linux? If you are using another operating system, please note that this package is **only for Linux platforms**! If you are using another operating system please use the upstream package, [`platformio-ide-terminal`](https://github.com/platformio/platformio-atom-ide-terminal).
* Are you running the [latest version of Atom](https://github.com/atom/atom/releases/latest)? If not, please upgrade and see if your bug still exists.
* Did you [search](https://github.com/issues?q=is%3Aissue+user%3Afusion809+-repo%3Aterminal-fusion) through the previously reported issues reported for this repository?

### Description

[Description of the bug or feature]

I have simple bash script which has "cd" command
when I launched it via terminal-fusion.

all other commands recognized and executed but not "cd" command.

examples

#!/bin/bash
cd /home/mika/remotesite     <---- won't work
pwd                                        <--- works fine
cp file1 /home/mika               <--- works fine
clear                                      <--- works fine
echo "copied successfully"    <--- works fine

### Steps to Reproduce

Expected behaviour: [What you expected to happen]

move into folder
Actual behaviour: [What actually happened]

nothing happend

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you are running. For example, if you were using Arch Linux with the 4.7.5-ARCH kernel, you would report that your OS is Arch Linux and your kernel version is 4.7.5-ARCH. To determine your kernel version run `uname -r`.

bash version:
GNU bash, version 4.3.30(1)-release (x86_64-pc-linux-gnu)
Terminal-fusion version 2.4.4
Atom 1.12.2
3.19.0-32-generic

cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"

**Comment by fusion809** [comment]
Ah my issue template exists for a very good reason mate. Here is a line in it I think you have ignored or raced past:

> Are you running the latest version of Atom? If not, please upgrade and see if your bug still exists.

This is relevant as you're using Atom 1.12.2, and 1.18.0 is the latest stable version. So if you want support upgrade to 1.18.0 and see if the bug persists. For me it doesn't occur on Arch Linux with Atom 1.18.0, as `cd` works fine. If it doesn't persist please close this bug.

**Comment by fusion809** [comment]
OK closing, if you upgrade and the bug persists feel free to re-open.
