### ISSUE TITLE
shortcut keys not working in mac os!

### ISSUE THREAD

**Issue by gholami-mohammad** [fusion809/terminal-fusion#2]
I install this terminal plugin but it's shortcuts not working for me!

**Comment by fusion809** [comment]
Sorry, but this Atom package is meant for Linux only. To quote the [README](https://github.com/fusion809/terminal-fusion/blob/master/README.md):

> It has been forked from the platformio-ide-terminal package, and is designed specifically for Linux platforms. If you are using macOS or Windows NT I would recommend using the platformio-ide-terminal package instead.
