### ISSUE TITLE
insert text does not working

### ISSUE THREAD

**Issue by kguidonimartins** [fusion809/terminal-fusion#6]
`Insert text` shortcut does not working.

The cursor in file just jump to the next line after hit `Ctrl + Enter`. Even using the `Insert Text` after `Ctrl + Shift + p` does the same.

```
$ atom --version
Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

```
$ apm --version
apm  1.12.9
npm  3.10.5
node 4.4.5
python 3.5.2
git 2.7.4
```

```
$ uname -r
4.4.0-53-generic
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

**Comment by fusion809** [comment]
Thanks for reporting, I experience this bug too, so I fixed it in 412e63e, or v2.4.3. It seems like Atom's core keybindings conflict with using <kbd>Ctrl</kbd>+<kbd>Enter</kbd> for this, so I changed it to <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>E</kbd>. To get the fix merely run:

```bash
$ apm update --no-confirm
```

where `$` indicates a standard (non-root) user console.
